name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade --user pip poetry
    - name: Build and publish
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry publish --repository testpypi -u __token__ -p ${{ secrets.TEST_PYPI_TOKEN }}  --build
